workflows:
    ios-sonarcloud:
      name: iOS sonarcloud
      instance_type: mac_mini
      environment:
        vars:
          XCODE_PROJECT: "swiftqube.xcodeproj"
          XCODE_SCHEME: "swiftqube"
          BUNDLE_ID: "io.codemagic.swiftqube"
          SONAR_TOKEN: fdd2e1ec1b6a9fcabaf5f7735777c4c894037413
        xcode: 12.5
        cocoapods: default
      triggering:
        events:
          - push
        branch_patterns:
          - pattern: main
            include: true
            source: true
      scripts:
        - name: Install Sonar Scanner
          script: | 
            brew install sonar-scanner
        - name: Generate debug build
          script: | 
            xcodebuild \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 12 Pro,OS=14.5' \
            -derivedDataPath Build/ \
            -enableCodeCoverage YES \
            clean build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
        - name: Convert coverage report to SonarCloud format
          script: |             
            bash xccov-to-sonarqube-generic.sh Build/Logs/Test/*.xcresult/ > sonarcloud-generic-coverage.xml
        - name: Generate and upload code analysis report
          script: |  
            export PATH=$PATH:$FCI_BUILD_DIR/sonar-scanner/bin
            
            sonar-scanner \
            -Dsonar.organization=sonar-org-1 \
            -Dsonar.projectKey=My-Github-Test-Orga_ios-sonarcloud-sample-project \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN \
            -Dsonar.coverageReportPaths=sonarcloud-generic-coverage.xml \
            -Dsonar.cfamily.build-wrapper-output.bypass=true \
            -Dsonar.c.file.suffixes=- \
            -Dsonar.cpp.file.suffixes=- \
            -Dsonar.objc.file.suffixes=- \

